# Generated by Django 5.0 on 2026-03-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='thumbnai_url',
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_link',
            field=models.URLField(verbose_name='作品リンク'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=50, verbose_name='作品名'),
        ),
    ]
