# Generated by Django 5.0 on 2026-03-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_thumbnai_url_game_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to='games/'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Scratch', 'scratch'), ('Unity', 'unity')], default='scratch', max_length=10, verbose_name='Unity or Scratch'),
        ),
    ]
