# Generated by Django 5.0 on 2026-03-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_game_file_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_link',
            field=models.URLField(blank=True, null=True, verbose_name='作品リンク'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('scratch', 'スクラッチ'), ('unity', 'Unity')], default='scratch', max_length=10, verbose_name='Unity or Scratch'),
        ),
    ]
