# Generated by Django 5.0 on 2026-03-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_game_link_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('scratch', 'スクラッチ'), ('unity', 'Unity')], max_length=10, verbose_name='Unity or Scratch'),
        ),
    ]
