# Generated by Django 5.0 on 2026-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creater',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='作者'),
        ),
    ]
