# Generated by Django 5.0 on 2026-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='school',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='作者'),
        ),
    ]
