# Generated by Django 5.0 on 2026-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='school',
            field=models.CharField(blank=True, choices=[('eifuku', '永福町'), ('goutokuji', '豪徳寺'), ('odakyuSagamihara', '小田急相模原')], max_length=20, null=True, verbose_name='所属校舎'),
        ),
    ]
