# Generated by Django 5.0 on 2026-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_creater_alter_game_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='concours',
            field=models.TextField(blank=True, choices=[('Gold', '金賞'), ('Silver', '銀賞'), ('Bronze', '銅賞')], null=True),
        ),
    ]
