# Generated by Django 5.0 on 2026-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_concours'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='department',
            field=models.TextField(blank=True, choices=[('J', 'ジュニア'), ('A', 'アドバンス'), ('S', 'スタンダード')], null=True),
        ),
    ]
