# Generated by Django 5.0 on 2026-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='school',
            field=models.CharField(blank=True, choices=[(1, '永福町'), (2, '豪徳寺'), (3, '久我山'), (4, '小田急相模原')], max_length=25, null=True, verbose_name='所属校舎'),
        ),
    ]
